### ISSUE TITLE
Avoid loading already registered definitions

### ISSUE THREAD

**Issue by doorgan** [WebReflection/uce-loader#1]
Let's say I have a chat element that displays chat messages as they are sent/arrive:

```js
define("my-chat", class extends HTMLElement{
  // overly simplyfied code
  render() {
    this.html`
      ${this.messages.map(message => html`<my-chat-message .message=${message} />`)}
      <input type="text" placeholder="Send a message"/>
    `;
  }
})
```

When the first message is sent, the `my-chat-message` element is discovered and fetched. This causes a delay between pressing Enter and the message being displayed. This is easily avoided by `import`ing the chat message element in the chat element, basically the parent imports all the elements it needs, but `uce-loader` won't know about it and will fetch the definition and add a script tag anyways.

I think this could be adressed by adding a `!customElements.get(is)` check [here](https://github.com/WebReflection/uce-loader/blob/master/esm/index.js#L29) and keeping the same api, or by exposing a `load(tag)` function to manually load definitions.

What's your opinion on this?

**Comment by WebReflection** [comment]
the `customElements.get(is)` check won't happen, because elements are defined only after these are fetched so that would require potentially the same element that's waiting for its definition to happen multiple times so ... nope.

exposing the loader could be done, but that's exactly as having a `<script>` in the page that points at the element definition, right?

**Comment by WebReflection** [comment]
On a second though, why don't *you* check that in the options?

```js
loader({
    on(newTag) {
      if (customElements.get(newTag)) return;
      const js = document.createElement('script');
      js.src = `js/components/${newTag}.js`;
      document.head.appendChild(js);
    }
  });
```

I could add that to the code, but if anyone was using this script to be notified about *every* custom element encountered in the page, such change would break their expectations, as that's a very valid use case to me ... what do you think?

should I bump major instead and avoid calling the `options.on(tag)` if already in the registry?

**Comment by WebReflection** [comment]
OK, I've bumped major, explained in the README the difference, and now the loader is not invoked if the element is already known. I hope this works fine 👋

**Comment by doorgan** [comment]
> if anyone was using this script to be notified about every custom element encountered in the page, such change would break their expectations, as that's a very valid use case to me

That's true. My reasoning was that the library's focus is on lazy loading components, so I expected it to notify me about unknown elements only. It's also true that `uce-loader` and an hypothetical `uce-observer` that notifies about *every* discovered custom element have lots of overlaps(it would be basically the same code sans the registered check), but I think the new behavior is more sensible considering the(most common?) lazy loading use case.

> OK, I've bumped major, explained in the README the difference, and now the loader is not invoked if the element is already known. I hope this works fine

Works like a charm, thank you!

PS: Merry Christmas!
